FROM mcr.microsoft.com/devcontainers/base:bookworm


USER vscode

ENV SHELL /bin/zsh

RUN mkdir -p ~/.local/share/zsh/plugins && ln -s /usr/share/zsh/plugins/powerlevel10k ~/.local/share/zsh/plugins/


# "build": {
#   "dockerfile": "Dockerfile",
#   "context": ".."
# },