FROM python:alpine as az

RUN echo "UTC" > /etc/timezone

RUN apk update && \
  apk add build-base \
  cargo \
  coreutils \
  curl \
  gcc \
  git \
  libffi-dev \ 
  make \
  musl-dev \
  nodejs \
  openssl-dev \
  python3-dev \
  shadow \
  sudo \
  unzip \
  wget 
RUN pip install --upgrade pip
RUN pip install azure-cli
